### PR TITLE
[Tabled until #29 lands] removing unclear reference to publish-mode

### PR DESCRIPTION
**Pull request by pdg744**
Partial solution to #38

### CODE REVIEW

**Review by tzerrell — COMMENTED** [review]
I think this is good but someone who knows a bit more about Bonsai than me should probably also review

**Review by capossele — COMMENTED** [review]
I think all of this has been already reworked in #29

**Comment by pdg744** [comment]
Converting this back to draft -- will re-visit this after #29 lands

**Comment by pdg744** [comment]
Looks like this has been resolved with #29

**Pull request closed without merging**
