### PR TITLE
Add murky to remappings

### PR DESCRIPTION
**Pull request by capossele**
As far as I've understood, remappings of `risc0-ethereum` should be replicated to the foundry template as well, so `murky` has been added to that.

Closes https://github.com/risc0/risc0-ethereum/issues/25

### CODE REVIEW

**Comment by capossele** [comment]
@Cardosaum can you confirm that this fixes your issues?

**Comment by nategraf** [comment]
I hit a similar issue I think, with the root cause for me being that I only shallow clones the submodules.

**Comment by Cardosaum** [comment]
Unfortunately, it does not fix all remapping issues, as even with `murky` itself I'm getting broken dependencies. 
It seems to me that remappings from `risc0-ethereum` interfere with remappings in the template, I'm not exactly sure what is happening yet.

**Comment by Cardosaum** [comment]
Based on a call we had yesterday, seems like this change does solve one of the issues we had with `remappings.txt`. 
We still have some compilation errors, but they're derived from other things.

**Review by Cardosaum — APPROVED** [review]

**Pull request merged**
