### PR TITLE
Support end-to-end flow with Bonsai in forge test and local deployment

### PR DESCRIPTION
**Pull request by nategraf**
This PR ports the modifications and improvements I worked on for the Governance showcase back to the
template. Included changes are:

* In `forge test`, optional request a SNARK from the Bonsai proving service and provide it to authenticate the callback, using the real SNARK verifier implementation (`BonsaiRelay`). This flow is enabled when `RISC0_DEV_MODE=false` is set and uses the full implementations of all components except the Bonsai Relay.
* By running `cargo run --bin bonsai-ethereum-relay-cli -- run`, developers can launch the Bonsai relay. With this, they can either target a a local Ethereum node with `anvil` or a public Ethereum network like Sepolia. This supports both local and testnet deployment of the developers's application.

Additionally:

* Declare `github.com/risc0/risc0` as a dependency and use the contained Bonsai libraries.
* Format and add new content to README.md
* Use workspace-level dependency declarations.

Resolves https://github.com/risc0/bonsai-foundry-template/issues/26
Resolves https://github.com/risc0/bonsai-foundry-template/issues/27
Resolves https://github.com/risc0/bonsai-foundry-template/issues/28

### CODE REVIEW

**Comment by nategraf** [comment]
Remaining work is to update and test the local deployment script.

**Comment by nategraf** [comment]
Depends on additions to the Bonsai libraries in https://github.com/risc0/risc0/pull/712

**Comment by nategraf** [comment]
@capossele, I've now added a more complete deploy script and run the local deployment. The local environment example doesn't work yet because the Relay does not support the `BonsaiRelay` and `BonsaiTestRelay` contracts.

**Comment by capossele** [comment]
Replaced by #45

**Pull request closed without merging**
