### PR TITLE
adding short videos to readme

### PR DESCRIPTION
**Pull request by pdg744**
This adds two brief videos to the readme to help new users orient themselves.

### CODE REVIEW

**Comment by mothran** [comment]
Doing inline iframes wont render in the README:
https://github.com/risc0/bonsai-foundry-template/blob/c2edd8fd19e7a111156724be27f1872df0537abe/README.md

Best to probably link to it instead.

**Comment by pdg744** [comment]
Interestingly, dragging an mp4 file directly into the github file editor imports the file as an asset and makes it available directly in the readme.

**Comment by pdg744** [comment]
What do folks think of this approach?

**Review by mothran — APPROVED** [review]
Looks good to me! TIL about embedding videos like that.

**Pull request merged**
